install:
  - curl -sLo - https://github.com/moul/travis-docker/raw/master/install.sh | sh -xe

script:
  - echo "==> Building the main Docker image..."
  - ./run 'docker build -f test/Dockerfile-ubuntu14.04 -t nodejs_img .  &&  docker run -i nodejs_img > result-ubuntu14.04'
  - ./run 'docker build -f test/Dockerfile-ubuntu12.04 -t nodejs_img .  &&  docker run -i nodejs_img > result-ubuntu12.04'
  - ./run 'docker build -f test/Dockerfile-debian8     -t nodejs_img .  &&  docker run -i nodejs_img > result-debian8    '
  - ./run 'docker build -f test/Dockerfile-debian7     -t nodejs_img .  &&  docker run -i nodejs_img > result-debian7    '
  - ./run 'docker build -f test/Dockerfile-centos7     -t nodejs_img .  &&  docker run -i nodejs_img > result-centos7    '
  - ./run 'docker build -f test/Dockerfile-centos6     -t nodejs_img .  &&  docker run -i nodejs_img > result-centos6    '

  - echo "==> Validating the test results..."
  - [ -s result-ubuntu14.04 ]  ||  exit 1
  - [ -s result-ubuntu12.04 ]  ||  exit 1
  - [ -s result-debian8     ]  ||  exit 1
  - [ -s result-debian7     ]  ||  exit 1
  - [ -s result-centos7     ]  ||  exit 1
  - [ -s result-centos6     ]  ||  exit 1
